# deployment.yaml for nginx1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  annotations: 
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:latest"
          ports:
            - containerPort: 80
              readinessProbe:
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
                path: /
                port: 80
            failureThreshold: 2
            initialDelaySeconds: 13
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
                path: /
                port: 80
            failureThreshold: 2
            initialDelaySeconds: 14
            periodSeconds: 10
            timeoutSeconds: 5
