# deployment.yaml for nginx1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:latest"
          ports:
            - containerPort: 80
              readinessProbe:
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 60
            periodSeconds: 21
          readinessProbe:
            httpGet:
                path: /
                port: 80
            failureThreshold: 2
            initialDelaySeconds: 23
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
                path: /
                port: 80
            failureThreshold: 2
            initialDelaySeconds: 24
            periodSeconds: 10
            timeoutSeconds: 5
