# job.yaml for nginx1
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  labels:
    app: nginx
  annotations:
    #"helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-weight": "5"
    #"helm.sh/hook-delete-policy": before-hook-creation
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["echo", "$(date)"]
      restartPolicy: Never
  backoffLimit: 4